spring.application.name=forecsic


#For Blog
MONGODB_USERNAME="nodrinkdrive2033_db_user"
MONGODB_PASSWORD="VN1CdxvzPOAiF5iy"
MONGODB_URI="mongodb+srv://nodrinkdrive2033_db_user:VN1CdxvzPOAiF5iy@cluster0.klbcncj.mongodb.net"


#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=${DATABASE_NAME}
#spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.url=jdbc:postgresql://ep-noisy-glade-axosfzw2-pooler.c-4.us-east-2.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_GW15ECQtgowT
spring.jpa.hibernate.ddl-auto=update

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG

# JWT
#jwt.secret=${JWT_TOKEN}
jwt.secret=dGhpc0lzQVZlcnlMb25nU2VjcmV0S2V5Rm9ySldUU2lnbmluZ0F0TGVhc3QyNTZCaXRz
jwt.expiration-ms=86400000

# Resend Email Configuration
resend.api.key=${RESEND_API_KEY:}
resend.from.email=${RESEND_FROM_EMAIL:noreply@forensicpatrika.com}
# OTP Configuration
otp.expiration.minutes=10
